# Site wide configuration

title:            Dam Truong' Blog
locale:           en_US
url:              https://truongdam.github.io


# Jekyll configuration

permalink:   /:year/:month/:day/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  enable_coderay: false

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
  
# Site owner
owner:
  name: Dam Truong
  avatar: damtruong.png
  bio: "Vietnamese, Software Developer at @Evolable Asia, learn new things, research old things so become experts."
  email: hdtruong.cse@gmail.com
  disqus-shortname: damtruongblog
  twitter: #damtruong
  facebook: truonghndam
  google:
    plus: DamTruong88
    analytics: UA-1667243-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #truongdam
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: truong-dam-300877a7
  xing: #username
  instagram: #damtruong
  lastfm: #damtruong
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #damtruong
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

gems:
  - jekyll-sitemap
